# Generated by Django 4.1.5 on 2023-02-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculate',
        ),
    ]
