# Generated by Django 4.1.5 on 2023-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculatehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.FloatField(null=True)),
                ('electricity', models.FloatField(null=True)),
                ('newspaper', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'No')], max_length=200, null=True)),
                ('aluminium', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'No')], max_length=200, null=True)),
            ],
        ),
    ]
