# Generated by Django 4.1.5 on 2023-02-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_calculatehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Individual', 'Individual'), ('Organisation', 'Organisation')], max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='calculatehouse',
            name='aluminium',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Dont use', 'Dont use')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calculatehouse',
            name='newspaper',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Dont use', 'Dont use')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calculatehouse',
            name='calculate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.calculate'),
        ),
    ]
