# Generated by Django 4.1.5 on 2023-02-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_calculate_alter_calculatehouse_aluminium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
    ]
