# Generated by Django 4.1.5 on 2023-02-04 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_calculate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculatehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.FloatField(null=True)),
                ('electricity', models.FloatField(null=True)),
                ('newspaper', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Dont use', 'Dont use')], max_length=200, null=True)),
                ('aluminium', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Dont use', 'Dont use')], max_length=200, null=True)),
                ('calculate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.calculate')),
            ],
        ),
    ]
