# Generated by Django 4.1.5 on 2023-02-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_calculatehouse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculatehouse',
            new_name='Individual',
        ),
    ]
